### ISSUE TITLE
Stories + Layout broken after IG update

### ISSUE THREAD

**Issue by goro** [kurtextrem/Improved-for-Instagram#20]
There was an update to IG a few weeks ago and the layout has been broken for me since then:

![screen shot 2017-09-14 at 5 14 49 pm](https://user-images.githubusercontent.com/93427/30461097-7b7a9b6c-9970-11e7-9a13-a687e5f8333d.png)

Removing the `max-width` on the first child div of `section#mainFeed` and removing the second child div of it altogether (the "Stories" column) seems to restore things.

**Comment by kurtextrem** [comment]
Thank you, seems like it is a staged rollout as my layout wasn't changed.
I'm not home for the next two days, so I can't do much at the moment.
Fix will come on Sunday!

Am 15.09.2017 02:26 schrieb "Goro Harumi" <notifications@github.com>:

**Comment by kurtextrem** [comment]
Does the stories column come from a 3rd party extension?
Also, can you check which version of Improved for Instagram you've got? It removes the `max-width` like you said :)

**Comment by goro** [comment]
No, I don't have any other Instagram-related extensions installed. They must be doing a slow rollout (or country-specific one?). I've had your extension enabled for a while, so I don't even remember what it's supposed to look like normally :-)

I have version 2.3.2 of Improved for Instagram. Here's a gif of what I see in the DOM (without your extension enabled):

![cols](https://user-images.githubusercontent.com/93427/30515805-94f3f3f8-9ae3-11e7-8e9a-808be4b18afd.gif)

**Comment by kurtextrem** [comment]
I think the best solution would be to style the stories, to make them go horizontal, but that's not easy if I don't have it in front of me. However, I can try and you could report back if it worked.

Other method would be hiding the stories... which doesn't feel right.

**Comment by goro** [comment]
Yeah sure, I can test it out if you want.

Personally, I don't really care about the Stories stuff, but you're right, it would be kind of weird to hide them.

**Comment by kurtextrem** [comment]
I've just published v2.3.3, let me know if that works for you :)

**Comment by goro** [comment]
Sorry, it is still broken:

![screen shot 2017-09-17 at 10 04 53 am](https://user-images.githubusercontent.com/93427/30523087-c8ddda60-9b8f-11e7-96b0-8a85eb9f90c2.png)

You might need to wait to fix this until they've rolled out the update to your account-- getting that stories column and footer nav to fit in somehow could be a bit tricky as a lot would have to be changed there I think.

Adding `#mainFeed > div:first-child { max-width: none; }` fixes the articles, but that stories nav kind of ruins everything :man_shrugging::
 
![screen shot 2017-09-17 at 10 41 17 am](https://user-images.githubusercontent.com/93427/30523357-d2a1e30c-9b94-11e7-974b-769c8f7b5e1b.png)

Maybe something like this would look cool (had to change quite a bit to make this happen):

![screen shot 2017-09-17 at 10 53 41 am](https://user-images.githubusercontent.com/93427/30523466-92c109be-9b96-11e7-8f56-f0afc0a4b124.png)

For now, I've just added a `#mainFeed > div:last-child { display: none; }`. :-/

**Comment by kurtextrem** [comment]
Would you feel comfortable using https://chrome.google.com/webstore/detail/snappysnippet/blfngdefapoapkcdibbdkigpeaffgcil?utm_source=chrome-app-launcher-info-dialog to make a Codepen / JSFiddle out of the stories div only (alternatively pastebin just the html)? Having the HTML alone would definitely help modifying. 
If not, I'll go with your proposed solution.

**Comment by goro** [comment]
Yeah that's fine, here you go: http://jsfiddle.net/kuztykaq/

**Comment by kurtextrem** [comment]
Thanks a lot!

I know the following steps are less easy than just letting Chrome update the extension, but not sure how many iterations I may need to fix this issue. I've made quite a lot of progress based on your JSFiddle.

This is a test zip for the extension and requires the following steps to test:
1. Download, unzip anywhere
2. Go to chrome://extensions, top right check "Developer Mode"
3. Use the left most button that just appeared and select the folder where you had unzipped it.
(4. Disable the original Improved for Instagram while testing)

[dist.zip](https://github.com/kurtextrem/Improved-for-Instagram/files/1310179/dist.zip)

**Comment by goro** [comment]
Sorry, still broken: 

![screen shot 2017-09-18 at 8 14 53 pm](https://user-images.githubusercontent.com/93427/30574371-56b4d626-9cae-11e7-8820-c47eb814f432.png)

**Comment by kurtextrem** [comment]
Can you check whether my CSS overwrites IG's css, or not? (I might need to add `!important` to the CSS, not sure)

**Comment by goro** [comment]
Now, it's totally broken:

![ig](https://user-images.githubusercontent.com/93427/30624943-1141480a-9d75-11e7-9d00-6132bd60cb0e.gif)

I noticed that deleting the second div (the stories one) fixes the layout, though.

**Comment by kurtextrem** [comment]
I have added a thing to prevent this - but I'm not sure why it does this vertical thing. It is supposed to be row like, horizontal.

Revision 3:
[dist.zip](https://github.com/kurtextrem/Improved-for-Instagram/files/1316722/dist.zip)

**Comment by goro** [comment]
Sorry, it is still not working:
  
![screen shot 2017-09-22 at 7 07 02 am](https://user-images.githubusercontent.com/93427/30748312-c1f30706-9f64-11e7-909d-bc25c16421bc.png)

**Comment by kurtextrem** [comment]
Could you make a gif again that shows which element creates the huge white space?
And if possible, inspect one of the story items so I can see why they're not in one row.

**Comment by goro** [comment]
I think the big gap is being caused by the stories div being set to `width: 100%`. Setting that to `auto` makes the articles appear, but they are still pushed off the screen by the width of the stories div. Deleting the stories div still fixes everything:

![ig](https://user-images.githubusercontent.com/93427/30787574-baaa2cda-a140-11e7-9f4a-8a9611f5472a.gif)

Here are the story items:

![ig2](https://user-images.githubusercontent.com/93427/30787575-be26420e-a140-11e7-93a4-96b25ab0afd5.gif)

**Comment by kurtextrem** [comment]
The latest release version hides the story div, in case you want to use it :)

A new test zip, where I set `width` to `auto`:
[dist.zip](https://github.com/kurtextrem/Improved-for-Instagram/files/1328575/dist.zip)

**Comment by goro** [comment]
Hi, here's what it looks like now:

![ig3](https://user-images.githubusercontent.com/93427/30995470-43d827ec-a46f-11e7-9100-ae95c75e204c.gif)

Also, looks like the latest update put it all in a single column:

![screen shot 2017-09-28 at 5 09 06 pm](https://user-images.githubusercontent.com/93427/30995541-c7872480-a46f-11e7-9ca9-144df5c9d2d3.png)

**Comment by kurtextrem** [comment]
Seems like IG rolled out an update. On a side note: They've added a virtual list, so only 8 items are displayed at the same time. That's huge!

Huge thanks for doing all the tests and gifs.

**Comment by kurtextrem** [comment]
And another test package for you:
[dist.zip](https://github.com/kurtextrem/Improved-for-Instagram/files/1346298/dist.zip)

**Comment by goro** [comment]
:man_shrugging:

![screen shot 2017-10-01 at 10 24 45 am](https://user-images.githubusercontent.com/93427/31057163-ccc0f99c-a692-11e7-9d1d-a4d6f45bf939.png)

**Comment by kurtextrem** [comment]
Hm.
I also wonder where the regular IG pictures go if they're not directly beneath the stories div? I've removed the float, so they should be under it.
This is so frustrating :|

**Comment by KLVN** [comment]
Works like a charm now 👌 Seems like Instagram rolled back some changes

**Comment by kurtextrem** [comment]
@KLVN Yeah, I've pushed out an update. However, this issue is about the stories and that still doesn't work :/

**Comment by KLVN** [comment]
I'm using your extension on Version 2.3.5 and Chrome IG Story (like suggested in the description) on Version 2.1.6 and everything works fine ¯\\\_(ツ)_/¯

**Comment by goro** [comment]
@kurtextrem So, just fyi, I noticed that changing `section#mainFeed` to `flex-direction: column` makes the layout not broken:

![screen shot 2017-10-03 at 6 09 49 pm](https://user-images.githubusercontent.com/93427/31155859-334ce0c0-a866-11e7-9ac2-880d3bbe24d8.png)

**Comment by kurtextrem** [comment]
@KLVN Yep :) Out of curiosity, do you see them?
@goro Added your fix! Now we just need to bring back the icons (you can use the official version again - I added everything there).

**Comment by KLVN** [comment]
> Yep :) Out of curiosity, do you see them?

Not yet, also tried clearing cache and using other user-agents.

___

> by the way boys

Did you just assume our genders? 🤔 :D

I answered the request :)

**Comment by kurtextrem** [comment]
> Not yet, also tried clearing cache and using other user-agents.
Same. Seems like it's an experiment? Or might be triggered when you follow not so many people, or special people?

> Did you just assume our genders? 🤔 :D
Uhm 👼 :D 
Thank you Kelvin!

**Comment by kurtextrem** [comment]
Great news! I just got the native stories it seems. I'm on fixing it finally.
